### ISSUE TITLE
mean functions are not compabtible with non-factor HID variables

### ISSUE THREAD

**Issue by alexkowa** [statistikat/surveysd#12]
works:
`surveysd::arithmetic_mean(c(1.0,2.0,3.0),factor(c("A","B","C")))`

does not work:
`surveysd::arithmetic_mean(c(1.0,2.0,3.0),c(1L,2L,3L))`
`surveysd::arithmetic_mean(c(1.0,2.0,3.0),c("A","B","C"))`
`surveysd::arithmetic_mean(c(1.0),c(1L))`

the same is true for geometric_mean, this leads to errors in ipf if the hid variable is not a factor

**Comment by alexkowa** [comment]
additional we should probably remove them from the exports, because you can crash a session with:
`surveysd::geometric_mean(c(1.0,2.0,3.0),factor(c("A")))`

alternatively the functions need more sanity input checks

**Comment by GregorDeCillia** [comment]
If we remove those functions from the exports there should be no need to change the implementation of these functions. That is, because ipf automatically converts some columns to factors before the iteration starts.

https://github.com/statistikat/surveysd/blob/9c78702ce2a655913766fa2d1046113848e42c95/R/ipf.r#L602-L606

Is there a use-case where this behavior occurs after a call to ipf?

**Comment by alexkowa** [comment]
The example fails if the line for converting household into a factor is commented
```
data(eusilcS,package="simPop")
library(data.table)
setDT(eusilcS)
eusilcS <- eusilcS[, list(db030,hsize,db040,age,rb090,netIncome,db090,rb050)]

## rename columns
setnames(eusilcS, "rb090", "gender")
setnames(eusilcS, "db040", "state")
setnames(eusilcS, "db030", "household")
setnames(eusilcS, "rb050", "weight")

## some recoding
# generate age groups
eusilcS[, agegroup := cut(age, c(-Inf, 10*1:9, Inf), right = FALSE)]
# some recoding of netIncome for reasons of simplicity
eusilcS[is.na(netIncome), netIncome := 0]
eusilcS[netIncome < 0, netIncome := 0]
# set hsize to 1,...,5+
eusilcS[, hsize := cut(hsize, c(0:4, Inf), labels = c(1:4, "5+"))]
#######################
#######################
# treat households as a factor variable
#eusilcS[, household := as.factor(household)]
#######################
#######################
## example for base weights assuming a simple random sample of households
## stratified per region
eusilcS[, regSamp := .N, by = state]
eusilcS[, regPop := sum(weight), by = state]
eusilcS[, baseWeight := regPop/regSamp]

## constraints on person level
# age
conP1 <- xtabs(weight ~ agegroup, data = eusilcS)
# gender by region
conP2 <- xtabs(weight ~ gender + state, data = eusilcS)
# personal net income by gender
conP3 <- xtabs(weight*netIncome ~ gender, data = eusilcS)

## constraints on household level
conH1 <- xtabs(weight ~ hsize + state, data = eusilcS,
               subset = !duplicated(household))

# array of convergence limits for conH1
epsH1 <- conH1
epsH1[1:4,] <- 0.005
epsH1["5+",] <- 0.2

# without array epsH1

calibweights1 <- ipf(eusilcS, hid = "household",
                     conP = list(conP1, conP2, netIncome = conP3),
                     conH = list(conH1),
                     epsP = list(1e-06, 1e-06, 1e-03),
                     epsH = 0.01,
                     bound = NULL, verbose = TRUE,  maxIter = 200)
```

**Comment by GregorDeCillia** [comment]
For reference: The problem was that the automatic conversion to factors was applied to all "grouping variables" occuring in `epsP` and `epsH` 

```r
for (col_name in names(dimnames(epsP)))
  # type conversion logic
```

but not for the household variable itself. The functions `geometric_mean` and `arithmetic_mean` have been removed from the exports, altough they are still documented.

Possible TODOs:

- [ ] See whether `ìpf_step` and friends show a similar behavior. Theose functions have also been developed with a "performance first" mindset
- [ ] Rethink if it makes sense to even document the now non-exported functions `geometric_mean` and `arithmetic_mean`
- [ ] Add some unit tests with "bad types" in the data
