### ISSUE TITLE
ipf() shows convergence message but did not converge

### ISSUE THREAD

**Issue by JohannesGuss** [statistikat/surveysd#26]
Problem seems to occur when using `computeLinear()` or `computeLinearG1()` and setting `bound` very high

```r
dat <- data.table(ID = 1:3, h = 1, USB = c(15000, 500, 250))
con1 <- xtabs(N ~ h, data = data.frame(h = 1, N = 1100))
con2 <- xtabs(Nusb ~ h, data = data.frame(h = 1, Nusb = 165000))
dat[, w1 := 165000 / sum(USB)]

dat_calib <- ipf(dat, conP = list(con1, USB = con2), w = "w1", epsP = .05,
                 verbose = TRUE, bound = 1000, maxIter = 1000,
                 returnNA = FALSE, numericalWeighting = surveysd::computeLinearG1, 
                 meanHH = FALSE)
#> 10:Not yet converged for P-Constraint2
#> 
#> 20:Not yet converged for P-Constraint2
#> 
#> 30:Not yet converged for P-Constraint2
#>  
#> 40:Not yet converged for P-Constraint2
#> 
#> Convergence reached in 41 steps
```

Margins using calibrated weights do however not align with constraints

```r
# using calibrated weights
dat_calib[,.(sum(calibWeight),sum(calibWeight*USB))]
#>          V1       V2
#>  1: 1125.868 296475.8

# constraints
con1kh
#> h
#>    1 
#> 1100 
con2
#> h
#>     1 
#> 165000 
```

**Comment by GregorDeCillia** [comment]
The problem here is the convergence criterion

https://github.com/statistikat/surveysd/blob/9cad3deb421b99ce7a5ba41e121da8aba49850d4/R/ipf.r#L292

It basically checks whether the iteration step applied significant changes to the weights or not. `fVariableForCalibrationIPF` is the quotient of the weights before the step to the weights after the step.

In case of `surveysd::computeLinearG1`, it is possible that the weights only change minimally due to "trimming". Maybe we should use the following criterion instead

```r
all(abs((conP[[i]] - conP_calib[[i]])/conP[[i]])) < eps
```

This could be calculated for all constraints after every iteration step. However, this criterion is wiedly different from the one currently used so we would have to make this optional for backwards compability.

**Comment by GregorDeCillia** [comment]
As discussed at the end of last week, I decided to not change the stopping criterion in the while loop. Instead, a more appropriate convergence check is applied after the iteration has stopped. 

Therefore, we will not need to worry about backwards compability. The only things that were changed from a user perspective are
- The console output if `verbose` is set to `TRUE`
- The attribute of the return value if ipf (`x <- ipf(...); attr(x, "converged")`)
